# Generated by Django 3.0.7 on 2020-07-23 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('address', models.EmailField(default='icFB5hrONTk@outtaoffice.work', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailboxDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to='connections.Mailbox')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_member', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='mailbox',
            name='members',
            field=models.ManyToManyField(related_name='mailbox_members', through='connections.MailboxDetail', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_owner', to='accounts.Profile'),
        ),
    ]
