# Generated by Django 3.0.7 on 2020-07-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='mailbox_type',
            field=models.CharField(choices=[('P', 'Private'), ('PL', 'Private Limited')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='ekEexoQuYMA@outtaoffice.work', max_length=254, unique=True),
        ),
    ]
