# Generated by Django 3.0.7 on 2020-08-03 23:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200724_2108'),
        ('connections', '0002_auto_20200724_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='8oYEDSyS8qY@outtaoffice.work', max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('created_on', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_topics', to='connections.Mailbox')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_topics', to='accounts.Profile')),
            ],
        ),
    ]
