# Generated by Django 3.0.7 on 2020-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20200804_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='email_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='M7qIas9TbFI@outtaoffice.work', max_length=254, unique=True),
        ),
    ]
