# Generated by Django 3.0.7 on 2020-08-06 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200724_2108'),
        ('connections', '0005_auto_20200805_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='uUGtXL8mXc0@outtaoffice.work', max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='member',
        ),
        migrations.CreateModel(
            name='TopicDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_member', to='accounts.Profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='connections.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='member',
            field=models.ManyToManyField(related_name='member_topics', through='connections.TopicDetail', to='accounts.Profile'),
        ),
    ]
