# Generated by Django 3.0.7 on 2020-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_auto_20200814_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='pYm_LIBb390@outtaoffice.work', max_length=254, unique=True),
        ),
    ]
