# Generated by Django 3.0.7 on 2020-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0011_auto_20200814_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='address',
            field=models.EmailField(default='dEP0FUAzMvU@outtaoffice.work', max_length=254, unique=True),
        ),
    ]
