# Generated by Django 3.0.7 on 2020-07-08 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(2)),
        ),
    ]
