# Generated by Django 3.0.7 on 2020-07-15 17:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
        ('items', '0002_auto_20200708_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='saved items', max_length=75)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('collections', models.ManyToManyField(related_name='_collection_collections_+', to='items.Collection')),
                ('items', models.ManyToManyField(to='items.Item')),
                ('owners', models.ManyToManyField(to='accounts.Profile')),
            ],
        ),
    ]
