# Generated by Django 3.0.7 on 2020-07-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
        ('items', '0003_auto_20200715_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='items_collections', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owners',
            field=models.ManyToManyField(related_name='owner_collections', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.Item'),
        ),
    ]
