# Generated by Django 3.0.7 on 2020-08-17 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0012_auto_20200817_0318'),
        ('items', '0004_auto_20200715_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='connections.Topic'),
        ),
    ]
